//
//  JSONValueTransformer+NSDate.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//

#import "JSONValueTransformer.h"

@interface JSONValueTransformer (NSDate)

-(NSDate*) NSDateFromNSString:(NSString*)string;

@end
