//
//  Driver.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#ifndef APIMATIC_DRIVER
#define APIMATIC_DRIVER

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol Driver
@end

@interface Driver : JSONModel

/**
* The first name of the driver.
*/
@property NSString* name;

/**
* The formatted phone number for contacting the driver.
*/
@property NSString* phoneNumber;

/**
* The URL to the photo of the driver.
*/
@property NSString* pictureUrl;

/**
* The driver's star rating out of 5 stars.
*/
@property double rating;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif