//
//  Driver.m
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#import "Driver.h"

@implementation Driver

/**
* The first name of the driver.
*/
@synthesize name;

/**
* The formatted phone number for contacting the driver.
*/
@synthesize phoneNumber;

/**
* The URL to the photo of the driver.
*/
@synthesize pictureUrl;

/**
* The driver's star rating out of 5 stars.
*/
@synthesize rating;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"name": @"name",
        @"phone_number": @"phoneNumber",
        @"picture_url": @"pictureUrl",
        @"rating": @"rating"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end