//
//  ErrorBase.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#ifndef APIMATIC_ERRORBASE
#define APIMATIC_ERRORBASE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Errors.h"


//protocol defined for deserialization of JSON
@protocol ErrorBase
@end

@interface ErrorBase : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSArray<Errors> * errors;

/**
* TODO: Write general description for this field
*/
@property NSString* meta;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif