//
//  GetProductsTypesInput.m
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#import "GetProductsTypesInput.h"

@implementation GetProductsTypesInput

/**
* Latitude component of location.
*/
@synthesize latitude;

/**
* Longitude component of location.
*/
@synthesize longitude;

@end