//
//  GetPriceEstimatesInput.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#ifndef APIMATIC_GETPRICEESTIMATESINPUT
#define APIMATIC_GETPRICEESTIMATESINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol GetPriceEstimatesInput
@end

@interface GetPriceEstimatesInput : NSObject

/**
* Latitude component of end location.
*/
@property double endLatitude;

/**
* Longitude component of end location.
*/
@property double endLongitude;

/**
* Latitude component of start location.
*/
@property double startLatitude;

/**
* Longitude component of start location.
*/
@property double startLongitude;

@end
#endif