//
//  GetPromotionsInput.m
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#import "GetPromotionsInput.h"

@implementation GetPromotionsInput

/**
* Latitude component of end location.
*/
@synthesize endLatitude;

/**
* Longitude component of end location.
*/
@synthesize endLongitude;

/**
* Latitude component of start location.
*/
@synthesize startLatitude;

/**
* Longitude component of start location
*/
@synthesize startLongitude;

@end