//
//  GetTimeEstimatesInput.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#ifndef APIMATIC_GETTIMEESTIMATESINPUT
#define APIMATIC_GETTIMEESTIMATESINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol GetTimeEstimatesInput
@end

@interface GetTimeEstimatesInput : NSObject

/**
* Latitude component of the start location
*/
@property double startLatitude;

/**
* Longitude component of the start location
*/
@property double startLongitude;

/**
* The customer id interested in estimate
*/
@property NSString* customerUuid;

/**
* Id of the requested product
*/
@property NSString* productId;

@end
#endif