//
//  GetTimeEstimatesInput.m
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#import "GetTimeEstimatesInput.h"

@implementation GetTimeEstimatesInput

/**
* Latitude component of the start location
*/
@synthesize startLatitude;

/**
* Longitude component of the start location
*/
@synthesize startLongitude;

/**
* The customer id interested in estimate
*/
@synthesize customerUuid;

/**
* Id of the requested product
*/
@synthesize productId;

@end