//
//  GetUserActivityV11Input.m
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#import "GetUserActivityV11Input.h"

@implementation GetUserActivityV11Input

/**
* Number of items to return for pagging
*/
@synthesize limit;

/**
* Page offset for pagging
*/
@synthesize offset;

@end