//
//  GetUserActivityV11Input.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#ifndef APIMATIC_GETUSERACTIVITYV11INPUT
#define APIMATIC_GETUSERACTIVITYV11INPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol GetUserActivityV11Input
@end

@interface GetUserActivityV11Input : NSObject

/**
* Number of items to return for pagging
*/
@property int limit;

/**
* Page offset for pagging
*/
@property int offset;

@end
#endif