//
//  History.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#ifndef APIMATIC_HISTORY
#define APIMATIC_HISTORY

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Location.h"


//protocol defined for deserialization of JSON
@protocol History
@end

@interface History : JSONModel

/**
* Distance travelled
*/
@property double distance;

/**
* Location where journey ended
*/
@property Location* endLocation;

/**
* Time of journey end
*/
@property int endTime;

/**
* The product that was used
*/
@property NSString* productId;

/**
* Time when requested
*/
@property int requestTime;

/**
* Location of starting the journey
*/
@property Location* startLocation;

/**
* Time of starting the journey
*/
@property int startTime;

/**
* Status of the product e.g., completed
*/
@property NSString* status;

/**
* History item id
*/
@property NSString* uuid;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif