//
//  Product.m
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#import "Product.h"

@implementation Product

/**
* Capacity of product. For example, 4 people.
*/
@synthesize capacity;

/**
* Description of product.
*/
@synthesize description;

/**
* Display name of product.
*/
@synthesize displayName;

/**
* Image URL representing the product.
*/
@synthesize image;

/**
* Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
*/
@synthesize productId;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"capacity": @"capacity",
        @"description": @"description",
        @"display_name": @"displayName",
        @"image": @"image",
        @"product_id": @"productId"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end