//
//  Product.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#ifndef APIMATIC_PRODUCT
#define APIMATIC_PRODUCT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol Product
@end

@interface Product : JSONModel

/**
* Capacity of product. For example, 4 people.
*/
@property int capacity;

/**
* Description of product.
*/
@property NSString* description;

/**
* Display name of product.
*/
@property NSString* displayName;

/**
* Image URL representing the product.
*/
@property NSString* image;

/**
* Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
*/
@property NSString* productId;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif