//
//  PromotionsResponse.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#ifndef APIMATIC_PROMOTIONSRESPONSE
#define APIMATIC_PROMOTIONSRESPONSE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol PromotionsResponse
@end

@interface PromotionsResponse : JSONModel

/**
* A localized string we recommend to use when offering the promotion to users.
*/
@property NSString* displayText;

/**
* The value of the promotion that is available to a user in this location in the local currency.
*/
@property NSString* localizedValue;

/**
* The type of the promo which is either "trip_credit" or "account_credit".
*/
@property NSString* type;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif