//
//  PromotionsResponse.m
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#import "PromotionsResponse.h"

@implementation PromotionsResponse

/**
* A localized string we recommend to use when offering the promotion to users.
*/
@synthesize displayText;

/**
* The value of the promotion that is available to a user in this location in the local currency.
*/
@synthesize localizedValue;

/**
* The type of the promo which is either "trip_credit" or "account_credit".
*/
@synthesize type;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"display_text": @"displayText",
        @"localized_value": @"localizedValue",
        @"type": @"type"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end