//
//  RequestBody.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#ifndef APIMATIC_REQUESTBODY
#define APIMATIC_REQUESTBODY

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol RequestBody
@end

@interface RequestBody : JSONModel

/**
* The final or destination latitude.
*/
@property double endLatitude;

/**
* The final or destination longitude.
*/
@property double endLongitude;

/**
* The unique ID of the product being requested.
*/
@property NSString* productId;

/**
* The beginning or "pickup" latitude.
*/
@property double startLatitude;

/**
* The beginning or "pickup" longitude.
*/
@property double startLongitude;

/**
* The unique identifier of the surge session for a user. Required when returned from a 409 Conflict response on previous POST attempt.
*/
@property NSString* surgeConfirmationId;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif