//
//  Request.m
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#import "Request.h"

@implementation Request

/**
* The object that contains driver details.
*/
@synthesize driver;

/**
* The estimated time of vehicle arrival in minutes.
*/
@synthesize eta;

/**
* The object that contains the location information of the vehicle and driver
*/
@synthesize location;

/**
* The unique ID of the Request.
*/
@synthesize requestId;

/**
* The status of the Request indicating state.
*/
@synthesize status;

/**
* The surge pricing multiplier used to calculate the increased price of a Request. A multiplier of 1.0 means surge pricing is not in effect.
*/
@synthesize surgeMultiplier;

/**
* The object that contains vehicle details.
*/
@synthesize vehicle;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"driver": @"driver",
        @"eta": @"eta",
        @"location": @"location",
        @"request_id": @"requestId",
        @"status": @"status",
        @"surge_multiplier": @"surgeMultiplier",
        @"vehicle": @"vehicle"  
    }];
    [map addEntriesFromDictionary: [super keyMap]];   

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end