//
//  RequestBody.m
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#import "RequestBody.h"

@implementation RequestBody

/**
* The final or destination latitude.
*/
@synthesize endLatitude;

/**
* The final or destination longitude.
*/
@synthesize endLongitude;

/**
* The unique ID of the product being requested.
*/
@synthesize productId;

/**
* The beginning or "pickup" latitude.
*/
@synthesize startLatitude;

/**
* The beginning or "pickup" longitude.
*/
@synthesize startLongitude;

/**
* The unique identifier of the surge session for a user. Required when returned from a 409 Conflict response on previous POST attempt.
*/
@synthesize surgeConfirmationId;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"end_latitude": @"endLatitude",
        @"end_longitude": @"endLongitude",
        @"product_id": @"productId",
        @"start_latitude": @"startLatitude",
        @"start_longitude": @"startLongitude",
        @"surge_confirmation_id": @"surgeConfirmationId"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end