//
//  RequestDetailsCollections.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#ifndef APIMATIC_REQUESTDETAILSCOLLECTIONS
#define APIMATIC_REQUESTDETAILSCOLLECTIONS

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Driver.h"
#import "Location.h"
#import "Vehicle.h"


//protocol defined for deserialization of JSON
@protocol RequestDetailsCollections
@end

@interface RequestDetailsCollections : JSONModel

/**
* The object that contains driver details.
*/
@property Driver* driver;

/**
* The estimated time of vehicle arrival in minutes.
*/
@property int eta;

/**
* The object that contains the location information of the vehicle and driver.
*/
@property Location* location;

/**
* The unique ID of the Request.
*/
@property NSString* requestId;

/**
* The status of the Request indicating state.
*/
@property NSString* status;

/**
* The surge pricing multiplier used to calculate the increased price of a Request. A multiplier of 1.0 means surge pricing is not in effect.
*/
@property double surgeMultiplier;

/**
* The object that contains vehicle details.
*/
@property Vehicle* vehicle;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif