//
//  Request.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#ifndef APIMATIC_REQUEST
#define APIMATIC_REQUEST

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "ErrorBase.h"


//protocol defined for deserialization of JSON
@protocol Request
@end

@interface Request : ErrorBase

/**
* The object that contains driver details.
*/
@property NSDictionary* driver;

/**
* The estimated time of vehicle arrival in minutes.
*/
@property int eta;

/**
* The object that contains the location information of the vehicle and driver
*/
@property NSDictionary* location;

/**
* The unique ID of the Request.
*/
@property NSString* requestId;

/**
* The status of the Request indicating state.
*/
@property NSString* status;

/**
* The surge pricing multiplier used to calculate the increased price of a Request. A multiplier of 1.0 means surge pricing is not in effect.
*/
@property double surgeMultiplier;

/**
* The object that contains vehicle details.
*/
@property NSDictionary* vehicle;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif