//
//  TimeEstimateCollection.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#ifndef APIMATIC_TIMEESTIMATECOLLECTION
#define APIMATIC_TIMEESTIMATECOLLECTION

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "TimeEstimate.h"


//protocol defined for deserialization of JSON
@protocol TimeEstimateCollection
@end

@interface TimeEstimateCollection : JSONModel

/**
* List of time estimates
*/
@property NSArray<TimeEstimate> * times;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif