//
//  UserProfile.m
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#import "UserProfile.h"

@implementation UserProfile

/**
* Email address of the Uber user
*/
@synthesize email;

/**
* First name of the Uber user.
*/
@synthesize firstName;

/**
* Last name of the Uber user.
*/
@synthesize lastName;

/**
* Image URL of the Uber user.
*/
@synthesize picture;

/**
* Promo code of the Uber user.
*/
@synthesize promoCode;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"email": @"email",
        @"first_name": @"firstName",
        @"last_name": @"lastName",
        @"picture": @"picture",
        @"promo_code": @"promoCode"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end