//
//  UserProfile.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#ifndef APIMATIC_USERPROFILE
#define APIMATIC_USERPROFILE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol UserProfile
@end

@interface UserProfile : JSONModel

/**
* Email address of the Uber user
*/
@property NSString* email;

/**
* First name of the Uber user.
*/
@property NSString* firstName;

/**
* Last name of the Uber user.
*/
@property NSString* lastName;

/**
* Image URL of the Uber user.
*/
@property NSString* picture;

/**
* Promo code of the Uber user.
*/
@property NSString* promoCode;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif