//
//  UserActivity.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#ifndef APIMATIC_USERACTIVITY
#define APIMATIC_USERACTIVITY

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "History.h"


//protocol defined for deserialization of JSON
@protocol UserActivity
@end

@interface UserActivity : JSONModel

/**
* Total number of items available.
*/
@property int count;

/**
* Information including the pickup location, dropoff location, request start time, request end time, and distance of requests (in miles), as well as the product type that was requested.
*/
@property NSArray<History> * history;

/**
* Number of items to retrieve (100 max).
*/
@property int limit;

/**
* Position in pagination.
*/
@property int offset;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif