//
//  Vehicle.h
//  UberAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
//
#ifndef APIMATIC_VEHICLE
#define APIMATIC_VEHICLE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol Vehicle
@end

@interface Vehicle : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* licensePlate;

/**
* TODO: Write general description for this field
*/
@property NSString* make;

/**
* TODO: Write general description for this field
*/
@property NSString* model;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif